"""Add Ingredient backref in Recipe table

Revision ID: 151f793be5ad
Revises: 813ff670e1ed
Create Date: 2023-08-20 06:08:19.742848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151f793be5ad'
down_revision: Union[str, None] = '813ff670e1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
