"""Add food group columns to the recipe table

Revision ID: 798451b62321
Revises: 7e72447f19e2
Create Date: 2023-08-19 17:46:53.537659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798451b62321'
down_revision: Union[str, None] = '7e72447f19e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vegetables_and_fruit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('breads_and_cereals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dairy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fats_and_sugar', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('fats_and_sugar')
        batch_op.drop_column('meat')
        batch_op.drop_column('dairy')
        batch_op.drop_column('breads_and_cereals')
        batch_op.drop_column('vegetables_and_fruit')

    # ### end Alembic commands ###
