"""Add measurement information to Ingredient table

Revision ID: 8abc738b4ff2
Revises: 151f793be5ad
Create Date: 2023-08-21 10:47:38.775396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abc738b4ff2'
down_revision: Union[str, None] = '151f793be5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_amount', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('measurement_unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('measurement_unit')
        batch_op.drop_column('measurement_amount')

    # ### end Alembic commands ###
