"""Attemp 2 to add backref for instructions and ingredients

Revision ID: 9daa553cd221
Revises: 05ba75aec7bc
Create Date: 2023-08-21 13:55:30.010835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9daa553cd221'
down_revision: Union[str, None] = '05ba75aec7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
