"""Remove backref from the Recipe table

Revision ID: c685112fc53f
Revises: 8abc738b4ff2
Create Date: 2023-08-21 12:16:12.019043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c685112fc53f'
down_revision: Union[str, None] = '8abc738b4ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
