"""make __table__ names plural

Revision ID: f7044c2d551c
Revises: c685112fc53f
Create Date: 2023-08-21 13:29:49.268759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7044c2d551c'
down_revision: Union[str, None] = 'c685112fc53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_title', sa.String(), nullable=True),
    sa.Column('vegetables_and_fruit', sa.Integer(), nullable=True),
    sa.Column('breads_and_cereals', sa.Integer(), nullable=True),
    sa.Column('dairy', sa.Integer(), nullable=True),
    sa.Column('meat', sa.Integer(), nullable=True),
    sa.Column('fats_and_sugar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_amount', sa.String(), nullable=True),
    sa.Column('measurement_unit', sa.String(), nullable=True),
    sa.Column('ingredient', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe')
    op.drop_table('ingredient')
    op.drop_table('instruction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('instruction', sa.VARCHAR(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient', sa.VARCHAR(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('measurement_amount', sa.VARCHAR(), nullable=True),
    sa.Column('measurement_unit', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_title', sa.VARCHAR(), nullable=True),
    sa.Column('vegetables_and_fruit', sa.INTEGER(), nullable=True),
    sa.Column('breads_and_cereals', sa.INTEGER(), nullable=True),
    sa.Column('dairy', sa.INTEGER(), nullable=True),
    sa.Column('meat', sa.INTEGER(), nullable=True),
    sa.Column('fats_and_sugar', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('instructions')
    op.drop_table('ingredients')
    op.drop_table('recipes')
    # ### end Alembic commands ###
